"""Renders the persistent event store to a friendly Markdown file."""
from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable
from zoneinfo import ZoneInfo

from dateutil import parser as dateparser

from .models import Event

# All display times are in Central. DFW is in America/Chicago which handles
# DST automatically (CST in winter, CDT in summer).
LOCAL_TZ = ZoneInfo("America/Chicago")


_HEADER = """# DFW Bachata & Salsa Events

> Auto-generated. Last update: **{updated}**
> Sources: {sources}
> {total} upcoming events tracked. **{new} new** since last run.
> All times shown in **Central** (DFW local).

---
"""

_FOOTER = """

---
*Generated by the DFW Dance Aggregator. Each event links back to where it was
found. If something looks off, the source link is the source of truth.*
"""


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DFW Bachata &amp; Salsa Events</title>
<style>
  /* Force light scheme so browser dark-mode forcing doesn't tint colors. */
  :root {{ color-scheme: light; }}
  * {{ box-sizing: border-box; }}
  html {{ background: #f7f7f8; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 880px; margin: 0 auto; padding: 24px 16px;
    line-height: 1.5; color: #111827; background: #f7f7f8;
  }}
  h1 {{ margin: 0 0 4px; font-size: 28px; color: #111827; }}
  .meta {{ color: #4b5563; font-size: 14px; margin-bottom: 24px; }}
  .filters {{ margin: 16px 0 24px; display: flex; gap: 8px; flex-wrap: wrap; }}
  .filters input[type=search] {{
    padding: 8px 12px; border: 1px solid #d1d5db; border-radius: 6px;
    font: inherit; flex: 1; min-width: 200px;
    background: #ffffff; color: #111827;
  }}
  .filters button {{
    padding: 8px 14px; border: 1px solid #d1d5db; border-radius: 6px;
    cursor: pointer; background: #ffffff; color: #111827; font: inherit;
  }}
  .filters button.active {{
    background: #2563eb; color: #ffffff; border-color: #2563eb;
  }}
  .new-banner {{
    background: #fff7ed; border: 1px solid #fdba74; color: #7c2d12;
    padding: 10px 14px; border-radius: 8px; margin-bottom: 18px; font-size: 14px;
  }}
  .day {{ border-top: 1px solid #e5e7eb; padding-top: 14px; margin-top: 24px; }}
  .day h2 {{ margin: 0 0 12px; font-size: 18px; color: #111827; }}
  .card {{
    background: #ffffff; border: 1px solid #e5e7eb; border-radius: 12px;
    padding: 14px 16px; margin-bottom: 10px;
    display: flex; gap: 14px; align-items: flex-start;
  }}
  .card.is-new {{ border-left: 4px solid #f97316; }}
  .card-body {{ flex: 1; min-width: 0; }}
  .card-head {{ display: flex; align-items: flex-start; gap: 10px; flex-wrap: wrap; }}
  /* All link states explicit so :visited / browser dark-mode tinting
     can't override our color choice. !important is the safety belt. */
  .card-title,
  .card-title:link,
  .card-title:visited,
  .card-title:hover,
  .card-title:active {{
    color: #0f172a !important;
    text-decoration: none; font-weight: 600;
    font-size: 16px; line-height: 1.3; flex: 1; min-width: 0;
  }}
  .card-title:hover {{ text-decoration: underline; }}
  .card .where {{ color: #4b5563; font-size: 14px; margin-top: 4px; }}
  .card .when {{ color: #4b5563; font-size: 14px; margin-top: 2px; }}
  .card .when .time {{ color: #2563eb; font-weight: 500; }}
  .card-thumb {{
    width: 64px; height: 64px; flex-shrink: 0; border-radius: 8px;
    background-size: cover; background-position: center; background-color: #f3f4f6;
  }}
  .tags {{ margin-top: 6px; }}
  .tag {{
    display: inline-block; background: #eef2ff; color: #3730a3;
    padding: 1px 8px; border-radius: 999px; font-size: 11px;
    margin-right: 4px; text-transform: lowercase;
  }}
  .price {{
    display: inline-block; padding: 3px 10px; border-radius: 999px;
    font-size: 12px; font-weight: 600; flex-shrink: 0;
    background: #dbeafe; color: #1e40af;
    border: 1px solid #bfdbfe;
  }}
  .price.free {{ background: #dcfce7; color: #166534; border-color: #bbf7d0; }}
  /* Soft neutral pill for "Varies" — meant to read as "check the link" without
     drawing as much attention as a confirmed price/free badge. */
  .price.varies {{ background: #f3f4f6; color: #6b7280; border-color: #e5e7eb;
                   font-weight: 500; }}
  .src {{ color: #6b7280; font-size: 12px; }}
  .empty {{ color: #6b7280; padding: 40px; text-align: center; }}
</style>
</head>
<body>
<h1>DFW Bachata &amp; Salsa Events</h1>
<div class="meta">
  Last update: <strong>{updated}</strong> &middot; {total} upcoming events &middot;
  Sources: {sources} &middot; All times Central (DFW local)
</div>

{new_banner}

<div class="filters">
  <input type="search" id="q" placeholder="Filter by venue, title, source...">
  <button data-tag="" class="active">All</button>
  <button data-tag="salsa">Salsa</button>
  <button data-tag="bachata">Bachata</button>
  <button data-tag="social">Socials</button>
  <button data-tag="lesson">Lessons</button>
  <button data-tag="workshop">Workshops</button>
  <button data-tag="free">Free only</button>
</div>

<div id="events">
{body}
</div>

<script>
  const q = document.getElementById('q');
  const buttons = document.querySelectorAll('.filters button');
  let activeTag = '';
  function apply() {{
    const term = q.value.trim().toLowerCase();
    document.querySelectorAll('.card').forEach(card => {{
      const matchesText = !term || card.dataset.search.includes(term);
      const matchesTag = !activeTag || (card.dataset.tags || '').split(' ').includes(activeTag);
      card.style.display = (matchesText && matchesTag) ? '' : 'none';
    }});
    document.querySelectorAll('.day').forEach(day => {{
      const visible = day.querySelectorAll('.card:not([style*="display: none"])').length;
      day.style.display = visible ? '' : 'none';
    }});
  }}
  q.addEventListener('input', apply);
  buttons.forEach(b => b.addEventListener('click', () => {{
    buttons.forEach(x => x.classList.remove('active'));
    b.classList.add('active');
    activeTag = b.dataset.tag;
    apply();
  }}));
</script>
</body>
</html>
"""


def render_html(
    events: Iterable[Event],
    out_path: Path,
    horizon_days: int = 90,
    new_window_hours: int = 26,
) -> None:
    """Write a self-contained interactive HTML page for browser viewing."""
    today = datetime.now(LOCAL_TZ).date()
    horizon = today + timedelta(days=horizon_days)
    new_since = datetime.now(timezone.utc) - timedelta(hours=new_window_hours)

    upcoming: list[Event] = []
    for ev in events:
        d = _local(_parse_dt(ev.start))
        if d is None or d.date() < today or d.date() > horizon:
            continue
        upcoming.append(ev)
    upcoming.sort(key=lambda e: _local(_parse_dt(e.start)) or _FAR_FUTURE)

    new_count = sum(1 for e in upcoming if _is_recent(e.first_seen_at, new_since))

    by_day: dict[date, list[Event]] = defaultdict(list)
    for ev in upcoming:
        d = _local(_parse_dt(ev.start))
        if d is not None:
            by_day[d.date()].append(ev)

    parts: list[str] = []
    if not by_day:
        parts.append('<div class="empty">No upcoming events found yet.</div>')
    for day in sorted(by_day.keys()):
        parts.append(f'<section class="day"><h2>{_fmt_day_header(day)}</h2>')
        for ev in by_day[day]:
            is_new = _is_recent(ev.first_seen_at, new_since)
            tags_html = "".join(
                f'<span class="tag">{_html_escape(t)}</span>'
                for t in (ev.tags or [])
            )
            where_bits = []
            if ev.venue:
                where_bits.append(_html_escape(ev.venue))
            if ev.city and (not ev.venue or ev.city.lower() not in ev.venue.lower()):
                where_bits.append(_html_escape(ev.city))
            where_html = (f'<div class="where">@ {", ".join(where_bits)}</div>'
                          if where_bits else "")
            tag_set = list(ev.tags or [])
            if ev.price:
                is_free = ev.price.lower().startswith("free")
                price_html = (
                    f'<span class="price{" free" if is_free else ""}">'
                    f'{_html_escape(ev.price)}</span>'
                )
                if is_free:
                    tag_set.append("free")
            else:
                # No structured price was extracted. Show a neutral "Varies"
                # pill so the user knows pricing exists but we couldn't pin
                # it down — they should click through to confirm.
                price_html = '<span class="price varies">Varies</span>'
            search_blob = " ".join(filter(None, [
                ev.title, ev.venue, ev.city, ev.source, ev.price,
                " ".join(tag_set),
            ])).lower()

            # Optional thumbnail (event flyer image, when available).
            thumb_html = ""
            if ev.image_url:
                thumb_html = (
                    f'<div class="card-thumb" '
                    f'style="background-image:url(\'{_html_escape(ev.image_url, attr=True)}\')">'
                    f'</div>'
                )

            # Inline "Day, Date • Time" line. Day comes from start_dt date.
            start_dt = _local(_parse_dt(ev.start))
            when_bits = []
            if start_dt:
                when_bits.append(_fmt_day_inline(start_dt.date()))
            when_bits.append(f'<span class="time">{_html_escape(_fmt_time(ev))}</span>')
            when_html = ' • '.join(when_bits)

            parts.append(
                f'<div class="card{" is-new" if is_new else ""}" '
                f'data-search="{_html_escape(search_blob, attr=True)}" '
                f'data-tags="{_html_escape(" ".join(tag_set), attr=True)}">'
                f'{thumb_html}'
                f'<div class="card-body">'
                f'<div class="card-head">'
                f'<a class="card-title" href="{_html_escape(ev.source_url, attr=True)}" '
                f'target="_blank" rel="noopener noreferrer">{_html_escape(ev.title)}</a>'
                f'{price_html}'
                f'</div>'
                f'{where_html}'
                f'<div class="when">{when_html}</div>'
                f'<div class="tags">{tags_html} <span class="src">via {_html_escape(ev.source)}</span></div>'
                f'</div>'   # /card-body
                f'</div>'   # /card
            )
        parts.append("</section>")

    sources = sorted({e.source for e in upcoming}) or ["—"]
    new_banner = (
        f'<div class="new-banner"><strong>{new_count} new event'
        f'{"s" if new_count != 1 else ""}</strong> since the last run.</div>'
        if new_count else ""
    )

    html = _HTML_TEMPLATE.format(
        updated=datetime.now(LOCAL_TZ).strftime("%Y-%m-%d %I:%M %p %Z"),
        total=len(upcoming),
        sources=", ".join(sources),
        new_banner=new_banner,
        body="\n".join(parts),
    )
    out_path.write_text(html, encoding="utf-8")


def _html_escape(s: str | None, *, attr: bool = False) -> str:
    if not s:
        return ""
    s = (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    if attr:
        s = s.replace('"', "&quot;")
    return s


def _parse_dt(s: str | None) -> datetime | None:
    if not s:
        return None
    try:
        return dateparser.parse(s)
    except (ValueError, TypeError):
        return None


def _aware(dt: datetime | None) -> datetime | None:
    """Force tz-awareness so sorts/compares don't blow up when some
    sources return naive datetimes and others return UTC-aware. Naive
    datetimes from iCal `DTSTART;VALUE=DATE` are assumed to be local
    Central time (DFW), which is the most useful default for this app."""
    if dt is None:
        return None
    if dt.tzinfo is None:
        return dt.replace(tzinfo=LOCAL_TZ)
    return dt


def _local(dt: datetime | None) -> datetime | None:
    """Convert to America/Chicago for display."""
    a = _aware(dt)
    return a.astimezone(LOCAL_TZ) if a else None


_FAR_FUTURE = datetime(9999, 1, 1, tzinfo=timezone.utc)


def _fmt_clock(dt: datetime) -> str:
    """7:00 PM (Windows strftime doesn't support %-I, so lstrip the zero)."""
    return dt.strftime("%I:%M %p").lstrip("0")


def _fmt_time(ev: Event) -> str:
    """Render start [- end] in local time. Examples:
       '7:00 PM', '7:00 PM – 11:00 PM', '11:00 PM – 2:00 AM', 'all day'."""
    start = _local(_parse_dt(ev.start))
    if not start:
        return "_TBD_"
    if start.hour == 0 and start.minute == 0:
        return "all day"
    end = _local(_parse_dt(ev.end))
    if not end or end <= start:
        return _fmt_clock(start)
    # Drop the date suffix even when the event crosses midnight; the day
    # heading already provides date context.
    return f"{_fmt_clock(start)} – {_fmt_clock(end)}"


def _fmt_day_header(d: date) -> str:
    return d.strftime("%A, %B %d, %Y").replace(" 0", " ")


def _fmt_day_inline(d: date) -> str:
    """Compact in-card date: 'Wed, May 6, 2026'."""
    return d.strftime("%a, %b %d, %Y").replace(" 0", " ")


def _is_recent(iso_ts: str | None, since: datetime) -> bool:
    dt = _aware(_parse_dt(iso_ts))
    if dt is None:
        return False
    return dt >= since


def render_markdown(
    events: Iterable[Event],
    out_path: Path,
    horizon_days: int = 90,
    new_window_hours: int = 26,   # a hair > 24h so daily cron always catches its own deltas
) -> None:
    """Write a single Markdown file grouped by date."""
    # All boundaries computed in local DFW time so a Friday 11pm event
    # doesn't get rolled over to "Saturday" by UTC.
    today = datetime.now(LOCAL_TZ).date()
    horizon = today + timedelta(days=horizon_days)
    new_since = datetime.now(timezone.utc) - timedelta(hours=new_window_hours)

    # Filter to upcoming, in-horizon events (local time).
    upcoming: list[Event] = []
    for ev in events:
        d = _local(_parse_dt(ev.start))
        if d is None:
            continue
        d_date = d.date()
        if d_date < today or d_date > horizon:
            continue
        upcoming.append(ev)

    upcoming.sort(key=lambda e: _local(_parse_dt(e.start)) or _FAR_FUTURE)

    # Group by day (local).
    by_day: dict[date, list[Event]] = defaultdict(list)
    for ev in upcoming:
        d = _local(_parse_dt(ev.start))
        if d is None:
            continue
        by_day[d.date()].append(ev)

    new_events = [e for e in upcoming if _is_recent(e.first_seen_at, new_since)]
    sources = sorted({e.source for e in upcoming}) or ["—"]

    parts: list[str] = []
    parts.append(_HEADER.format(
        updated=datetime.now(LOCAL_TZ).strftime("%Y-%m-%d %I:%M %p %Z"),
        sources=", ".join(sources),
        total=len(upcoming),
        new=len(new_events),
    ))

    if new_events:
        parts.append("## New since last run\n")
        for ev in new_events[:25]:
            parts.append(_render_event_line(ev, prefix="- "))
        parts.append("\n---\n")

    if not by_day:
        parts.append("\n_No upcoming events found yet. The aggregator will populate this on its next run._\n")
    else:
        parts.append("## Upcoming\n")
        for day in sorted(by_day.keys()):
            parts.append(f"\n### {_fmt_day_header(day)}\n")
            for ev in by_day[day]:
                parts.append(_render_event_line(ev, prefix="- "))

    parts.append(_FOOTER)
    out_path.write_text("\n".join(parts), encoding="utf-8")


def _render_event_line(ev: Event, prefix: str = "") -> str:
    """Stacked multi-line markdown entry, matching the visual hierarchy
    used by the latin-dance-guide reference app:
        - **[Title](url)** **_Free_**
          Venue · City
          Wed, May 6, 2026 • 7:00 PM – 11:00 PM
          `social` `salsa` _via salsavida_

    (Trailing two-space line-breaks render as <br> in markdown.)"""
    title_line_bits: list[str] = [f"**[{ev.title.strip()}]({ev.source_url})**"]
    title_line_bits.append(f"**_{ev.price or 'Varies'}_**")

    where_bits: list[str] = []
    if ev.venue:
        where_bits.append(ev.venue)
    if ev.city and (not ev.venue or ev.city.lower() not in ev.venue.lower()):
        where_bits.append(ev.city)
    where_line = " · ".join(where_bits) if where_bits else ""

    when_line_bits: list[str] = []
    start_dt = _local(_parse_dt(ev.start))
    if start_dt:
        when_line_bits.append(_fmt_day_inline(start_dt.date()))
    when_line_bits.append(_fmt_time(ev))
    when_line = " • ".join(when_line_bits)

    tags_line_bits: list[str] = []
    tag_str = " ".join(f"`{t}`" for t in (ev.tags or []))
    if tag_str:
        tags_line_bits.append(tag_str)
    tags_line_bits.append(f"_via {ev.source}_")
    tags_line = " ".join(tags_line_bits)

    # Build final block. Two trailing spaces force a markdown <br>.
    indent = " " * len(prefix.rstrip())   # keep continuation lines aligned
    lines: list[str] = [prefix + " ".join(title_line_bits) + "  "]
    if where_line:
        lines.append(f"{indent}  {where_line}  ")
    lines.append(f"{indent}  {when_line}  ")
    lines.append(f"{indent}  {tags_line}")
    return "\n".join(lines)
